version: '3'

services:
    php:
        container_name: php
        build:
            context: docker/php
        volumes:
            - ./:/var/www/symfony
    nginx:
        image: nginx
        restart: on-failure
        depends_on:
            - php
        ports:
            - 80:80
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

